# Copyright (c) 2026 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

load("//bazel:zephyr.bzl", "zephyr_west_build")
load("//bazel:manifest.bzl", "manifest_targets")
load("//bazel:image.bzl", "image_targets")
load("//bazel:pldm.bzl", "pldm_package")

zephyr_west_build(
    name = "cm4_bhs",
    board = "ast1080_dcscm_bhs",
    app = "aspeed-zephyr-project/apps/aspeed-pfr",
    output_bin = "zephyr-aspeed-pfr-bhs.bin",
    role = "cm4",
    visibility = ["//qemu:__pkg__"],
)

zephyr_west_build(
    name = "cm4_oks",
    board = "ast1080_dcscm_oks",
    app = "aspeed-zephyr-project/apps/aspeed-pfr",
    output_bin = "zephyr-aspeed-pfr-oks.bin",
    role = "cm4",
    visibility = ["//qemu:__pkg__"],
)

zephyr_west_build(
    name = "bootmcu",
    board = "ast1040_evb/ast1040/bootmcu",
    app = "aspeed-zephyr-project/apps/mcu-runtime",
    output_bin = "zephyr-mcu-runtime.bin",
    role = "bootmcu",
)

manifest_targets(
    platform = "ast1080",
    chip = "ast1080a0",
    name = "manifest_bhs",
    out_namespace = "ast1080a0-bhs",
    flash_image_out = "aspeed-manifest-flash-image-bhs.bin",
    cm4_target = ":cm4_bhs",
    manifest_cfg = "//ast1080/ast1080a0/manifest:ast1080a0-default-ecc-lms-mldsa-manifest.toml",
    ssmcu_runtime_target = "//ast1080/ast1080a0:ssmcu-runtime",
    bmc_pb_target = "//ast1080/ast1080a0:bmc-pb",
)

manifest_targets(
    platform = "ast1080",
    chip = "ast1080a0",
    name = "manifest_oks",
    out_namespace = "ast1080a0-oks",
    flash_image_out = "aspeed-manifest-flash-image-oks.bin",
    cm4_target = ":cm4_oks",
    manifest_cfg = "//ast1080/ast1080a0/manifest:ast1080a0-default-ecc-lms-mldsa-manifest.toml",
    ssmcu_runtime_target = "//ast1080/ast1080a0:ssmcu-runtime",
    bmc_pb_target = "//ast1080/ast1080a0:bmc-pb",
)

image_targets(
    platform = "ast1080",
    chip = "ast1080a0",
    name = "image_bhs",
    output_bin = "ast1080-bhs.bin",
    image_size_kb = 4096,
    ssmcu_rom_bin = "//ast1080/ast1080a0:ssmcu-rom-xip.bin",
    ssmcu_rom_seek_kb = 0,
    manifest_image = ":aspeed-manifest-flash-image-bhs.bin",
    manifest_image_seek_kb = 320,
    visibility = ["//qemu:__pkg__"],
)

pldm_package(
    name = "pldm_bhs",
    firmware_image = ":aspeed-manifest-flash-image-bhs.bin",
    manifest_template = ":ast1080a0-bhs-full-pldm-package.toml.tmpl",
    metadata_v1_0 = ":ast1080a0-bhs-full-pldm-package-v1.0.json",
    out = "ast1080-bhs-update.pldm",
    version_config = "@zephyr_ws//:ast1080_dcscm_bhs_pldm_config",
)

filegroup(
    name = "release_bhs",
    srcs = [
        ":image_bhs",
        ":pldm_bhs",
    ],
)

image_targets(
    platform = "ast1080",
    chip = "ast1080a0",
    name = "image_oks",
    output_bin = "ast1080-oks.bin",
    image_size_kb = 4096,
    ssmcu_rom_bin = "//ast1080/ast1080a0:ssmcu-rom-xip.bin",
    ssmcu_rom_seek_kb = 0,
    manifest_image = ":aspeed-manifest-flash-image-oks.bin",
    manifest_image_seek_kb = 320,
    visibility = ["//qemu:__pkg__"],
)

pldm_package(
    name = "pldm_oks",
    firmware_image = ":aspeed-manifest-flash-image-oks.bin",
    manifest_template = ":ast1080a0-oks-full-pldm-package.toml.tmpl",
    metadata_v1_0 = ":ast1080a0-oks-full-pldm-package-v1.0.json",
    out = "ast1080-oks-update.pldm",
    version_config = "@zephyr_ws//:ast1080_dcscm_oks_pldm_config",
)

filegroup(
    name = "release_oks",
    srcs = [
        ":image_oks",
        ":pldm_oks",
    ],
)
