# Copyright (c) 2026 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

load("//bazel:zephyr.bzl", "zephyr_west_build")
load("//bazel:manifest.bzl", "manifest_targets")
load("//bazel:image.bzl", "image_targets")

zephyr_west_build(
    name = "cm4",
    board = "ast1080_evb/ast1080/cm4",
    app = "zephyr/samples/subsys/shell/shell_module",
    output_bin = "zephyr-shell-module.bin",
    role = "cm4",
    visibility = ["//qemu:__pkg__"],
)

zephyr_west_build(
    name = "bootmcu",
    board = "ast1040_evb/ast1040/bootmcu",
    app = "aspeed-zephyr-project/apps/mcu-runtime",
    output_bin = "zephyr-mcu-runtime.bin",
    role = "bootmcu",
)

manifest_targets(
    platform = "ast1080",
    chip = "ast1080a0",
    cm4_target = ":cm4",
    manifest_cfg = "//ast1080/ast1080a0/manifest:ast1080a0-default-ecc-lms-mldsa-manifest.toml",
    ssmcu_runtime_target = "//ast1080/ast1080a0:ssmcu-runtime",
    bmc_pb_target = "//ast1080/ast1080a0:bmc-pb",
)

image_targets(
    platform = "ast1080",
    chip = "ast1080a0",
    image_size_kb = 4096,
    ssmcu_rom_bin = "//ast1080/ast1080a0:ssmcu-rom-xip.bin",
    ssmcu_rom_seek_kb = 0,
    manifest_image = ":aspeed-manifest-flash-image.bin",
    manifest_image_seek_kb = 320,
    visibility = ["//qemu:__pkg__"],
)
