# Copyright (c) 2026 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

load("//bazel:caliptra.bzl", "caliptra_targets")
load("//bazel:bmc_pb.bzl", "bmc_pb_target")

_PROFILE = "release"
_RISCV = "target/riscv32imc-unknown-none-elf/{}".format(_PROFILE)

bmc_pb_target(pb = [
    "ast1040a0/bootmcu-rom-xip.bin",
    "ast1040a0/caliptra-fw.bin",
    "ast1040a0/ssmcu-rom-xip.bin",
])

caliptra_targets(
    platform = "ast1040",
    profile = _PROFILE,
    ssmcu_runtime_bin = "{}/runtime-ast1040.bin".format(_RISCV),
    ssmcu_runtime_out = "ssmcu-runtime.bin",
)

caliptra_targets(
    platform = "ast1040",
    profile = _PROFILE,
    name = "ssmcu-runtime-streamingboot-i3c",
    ssmcu_runtime_bin = "{}/runtime-ast1040.bin".format(_RISCV),
    ssmcu_runtime_out = "ssmcu-runtime-streamingboot-i3c.bin",
    features = "test-pldm-streaming-boot",
    serialize_after = ":ssmcu-runtime",
)

exports_files(
    ["ast1040a0-pldm-package.toml.tmpl"],
    visibility = ["//visibility:public"],
)
