#!/usr/bin/env python3
"""Stage 256-byte-aligned streaming-boot-i3c images and generate an EVB runner."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import shutil
import stat
import tempfile


ALIGNMENT = 256
# i3cdev exposes the raw private-transfer ioctl used by i3ctransfer.
# The MCTP endpoint below is only used for streaming image data.
I3C_DEVICE = "/dev/bus/i3c/14-fffe005a10a5"
MCTP_DEVICE = "/dev/i3c-mctp-8"
MCTP_TOOL = "mctp-i3c-recovery_2755"


def align_and_copy(source: Path, destination: Path) -> int:
    """Copy source to destination and zero-pad it to ALIGNMENT bytes."""
    size = source.stat().st_size
    padding = (-size) % ALIGNMENT
    with source.open("rb") as src, destination.open("wb") as dst:
        shutil.copyfileobj(src, dst)
        if padding:
            dst.write(b"\0" * padding)
    return size + padding


def fifo_control_command(size: int) -> str:
    if size % 4:
        raise ValueError(f"streaming-boot image size {size} is not DWORD aligned")
    dwords = size // 4
    if dwords > 0xFFFFFFFF:
        raise ValueError(f"streaming-boot image is too large: {size} bytes")
    size_bytes = dwords.to_bytes(4, "little")
    fields = (0x2D, 0x06, 0x00, 0x00, 0x00, *size_bytes)
    return ",".join(f"0x{field:x}" for field in fields)


def write_runner(path: Path, images: list[tuple[str, int]]) -> None:
    lines = [
        "#!/bin/sh",
        "# Generated by gen_streamingboot_i3c_images.py; do not edit.",
        "set -eu",
        "",
        'IMG_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
        f'I3C_DEVICE="{I3C_DEVICE}"',
        f'MCTP_DEVICE="{MCTP_DEVICE}"',
        f'MCTP_TOOL="${{MCTP_TOOL:-$IMG_DIR/{MCTP_TOOL}}}"',
        "",
        'if [ ! -c "$I3C_DEVICE" ]; then',
        '    echo "missing raw I3C device: $I3C_DEVICE (load i3cdev)" >&2',
        "    exit 1",
        "fi",
        "",
        'if [ ! -x "$MCTP_TOOL" ]; then',
        '    echo "missing MCTP streaming-boot tool: $MCTP_TOOL" >&2',
        "    exit 1",
        "fi",
        "",
    ]
    for image, size in images:
        lines.extend(
            [
                f'echo "Send {image} ({size} bytes)"',
                f'i3ctransfer -d "$I3C_DEVICE" -w {fifo_control_command(size)}',
                f'"$MCTP_TOOL" -d "$MCTP_DEVICE" -f "$IMG_DIR/{image}"',
                '# RECOVERY_CTRL payload: CMS=0, image_selection=NoOperation(0), activate=0xf.',
                'i3ctransfer -d "$I3C_DEVICE" -w 0x26,0x3,0x0,0x0,0x0,0xf',
                "sleep 3",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--caliptra-fw", type=Path, required=True)
    parser.add_argument("--auth-manifest", type=Path, required=True)
    parser.add_argument("--ssmcu-runtime", type=Path, required=True)
    parser.add_argument("--mctp-tool", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--image-prefix", default="ast1040a0-default")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    outputs = [
        (args.caliptra_fw, "caliptra-fw_align_256.bin"),
        (args.auth_manifest, f"{args.image_prefix}-auth-manifest.bin"),
        (args.ssmcu_runtime, "ssmcu-runtime_align_256.bin"),
    ]
    for source, _ in outputs:
        if not source.is_file():
            raise SystemExit(f"missing input image: {source}")
    if not args.mctp_tool.is_file():
        raise SystemExit(f"missing MCTP streaming-boot tool: {args.mctp_tool}")

    args.output_dir.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=args.output_dir.parent, prefix=".streamingboot-i3c-") as tmp:
        staging = Path(tmp)
        images = []
        for source, output_name in outputs:
            size = align_and_copy(source, staging / output_name)
            assert size % ALIGNMENT == 0
            images.append((output_name, size))
        tool_destination = staging / MCTP_TOOL
        shutil.copy2(args.mctp_tool, tool_destination)
        tool_destination.chmod(tool_destination.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        write_runner(staging / "streamingboot_from_i3c.sh", images)

        if args.output_dir.exists():
            shutil.rmtree(args.output_dir)
        os.replace(staging, args.output_dir)


if __name__ == "__main__":
    main()
